name: Create Issue on Vulnerability in PR
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-alerts-and-file-issue:
    runs-on: ubuntu-latest
    permissions:
      security-events: read
      issues: write
      contents: write
    steps:
      - name: Wait briefly for Code Scanning to finish
        run: sleep 15

      - name: Fetch Code Scanning alerts
        id: cs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api -H "Accept: application/vnd.github+json" \
            "/repos/${{ github.repository }}/code-scanning/alerts?per_page=100&state=open" > cs.json
          echo "count=$(jq 'length' cs.json)" >> $GITHUB_OUTPUT

      - name: Prep issue body
        if: steps.cs.outputs.count != '0'
        run: |
          {
            echo "# Open Code Scanning Alerts for PR #${{ github.event.pull_request.number }}"
            jq -r '.[] | "- **\(.rule.id // .rule?.name // "rule")**: \(.most_recent_instance?.message?.text // "No message") [\(.html_url // "no link")]()"' cs.json
          } > ISSUE_BODY.md

      - name: Create Issue
        if: steps.cs.outputs.count != '0'
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Security alerts detected in PR #${{ github.event.pull_request.number }}"
          content-filepath: ISSUE_BODY.md
          labels: "security, automated"
